# Generated by Django 3.2.3 on 2021-06-23 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_registrousuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='cletaRevision',
            fields=[
                ('idbicicleta', models.AutoField(primary_key=True, serialize=False, verbose_name='id bicicleta')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo bicicleta')),
                ('porte', models.CharField(max_length=30, verbose_name='porte bicicleta')),
                ('aro', models.IntegerField(verbose_name='aro de rueda')),
                ('marca', models.CharField(max_length=50, verbose_name='marca bicicleta')),
                ('stock', models.IntegerField(verbose_name='cantidad tortas')),
                ('estado', models.CharField(max_length=50, verbose_name='marca bicicleta')),
            ],
        ),
    ]
