# Generated by Django 3.2.3 on 2021-06-25 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_cletarevision'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cletarevision',
            name='estado',
            field=models.CharField(max_length=50, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='cletarevision',
            name='modelo',
            field=models.CharField(max_length=50, verbose_name='modelo'),
        ),
        migrations.AlterField(
            model_name='cletarevision',
            name='porte',
            field=models.CharField(max_length=30, verbose_name='porte'),
        ),
        migrations.AlterField(
            model_name='cletarevision',
            name='stock',
            field=models.IntegerField(verbose_name='stock'),
        ),
    ]
